use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;
use syn::{Attribute, Expr, ExprLit, File, Item, Lit, Meta};

/// Status code value, symbolic name, and optional human-readable message.
type HaspErrorDetail = (u32, String, Option<String>);

pub fn extract_hasp_error_details(
    bindings_src: &str,
) -> Result<Vec<HaspErrorDetail>, Box<dyn std::error::Error>> {
    let ast: File = syn::parse_file(bindings_src)?;
    let enum_item = ast
        .items
        .iter()
        .find_map(|item| match item {
            Item::Enum(item_enum) if item_enum.ident == "hasp_error_codes" => Some(item_enum),
            _ => None,
        })
        .ok_or("hasp_error_codes enum not found in bindings.rs")?;

    let mut by_value = BTreeMap::<u32, (String, Option<String>)>::new();

    for variant in &enum_item.variants {
        let doc = extract_doc_message(&variant.attrs);
        let value = match &variant.discriminant {
            Some((
                _,
                Expr::Lit(ExprLit {
                    lit: Lit::Int(int_lit),
                    ..
                }),
            )) => int_lit.base10_parse::<u32>()?,
            _ => continue,
        };

        // The symbolic name always comes from the enum variant itself, so it's
        // recorded even when the header didn't have a doc comment for it. Only
        // the human-readable message is allowed to fall back to a generic default.
        by_value
            .entry(value)
            .or_insert((variant.ident.to_string(), doc));
    }

    Ok(by_value
        .into_iter()
        .map(|(value, (name, message))| (value, name, message))
        .collect())
}

fn extract_doc_message(attrs: &[Attribute]) -> Option<String> {
    let docs: Vec<String> = attrs
        .iter()
        .filter_map(|attr| match &attr.meta {
            Meta::NameValue(name_value) if name_value.path.is_ident("doc") => {
                match &name_value.value {
                    Expr::Lit(ExprLit {
                        lit: Lit::Str(lit_str),
                        ..
                    }) => Some(lit_str.value()),
                    _ => None,
                }
            }
            _ => None,
        })
        .collect();

    // Normalize away the leading space and any internal line-wrapping that
    // bindgen carries over from the C doc comments.
    let words: Vec<&str> = docs.iter().flat_map(|doc| doc.split_whitespace()).collect();
    (!words.is_empty()).then(|| words.join(" "))
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{{{:04x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// Renders `pub(crate) fn {fn_name}(code: u32) -> &'static str { match code { ... } }`
/// from `arms` (code, text), falling back to `default` for unmatched codes.
fn write_match_fn<'a>(
    out: &mut String,
    fn_name: &str,
    arms: impl Iterator<Item = (u32, &'a str)>,
    default: &str,
) {
    let _ = writeln!(out, "pub(crate) fn {fn_name}(code: u32) -> &'static str {{");
    let _ = writeln!(out, "    match code {{");
    for (value, text) in arms {
        let _ = writeln!(out, "        {value} => \"{}\",", escape_rust_string(text));
    }
    let _ = writeln!(out, "        _ => \"{default}\",");
    let _ = writeln!(out, "    }}\n}}");
}

pub fn generate_hasp_error_messages_rs(
    details: &[HaspErrorDetail],
    out_path: &Path,
) -> std::io::Result<()> {
    let mut out =
        String::from("// Generated by build.rs from bindgen docs on hasp_error_codes.\n\n");
    write_match_fn(
        &mut out,
        "hasp_status_name",
        details.iter().map(|(value, name, _)| (*value, name.as_str())),
        "UNKNOWN_HASP_STATUS",
    );
    out.push('\n');
    write_match_fn(
        &mut out,
        "hasp_status_message",
        details
            .iter()
            .filter_map(|(value, _, message)| Some((*value, message.as_deref()?))),
        "Unknown HASP status code",
    );
    fs::write(out_path, out)
}
